import React, { useState } from 'react';
import { AnalysisResult } from '@/types';
import { PromptForkDialog } from './PromptForkDialog';

interface AIAuditPanelProps {
    analysis: AnalysisResult;
    sourceId?: string;
    sourceTitle?: string;
    onFlagResult?: (reason: string) => void;
    onForkPrompt?: (newContent: string) => Promise<void>;
}

import { GovernanceService } from '@/services/governance/governance-service';

export function AIAuditPanel({ analysis, sourceId, sourceTitle, onFlagResult, onForkPrompt }: AIAuditPanelProps) {
    const governanceService = new GovernanceService();
    const [isExpanded, setIsExpanded] = useState(false);
    const [showPrompt, setShowPrompt] = useState(false);
    const [showThinking, setShowThinking] = useState(false);
    const [isFlagging, setIsFlagging] = useState(false);
    const [flagReason, setFlagReason] = useState("");
    const [showForkDialog, setShowForkDialog] = useState(false);

    const { metadata, provenance_chain } = analysis;
    const promptId = metadata?.prompt_id || 'unknown';
    const promptVersion = metadata?.prompt_version || 'unknown';

    // If no transparency data is available, don't render
    if (!metadata && !provenance_chain) return null;

    return (
        <div className="mt-8 border-t border-slate-700 pt-6">
            <button
                onClick={() => setIsExpanded(!isExpanded)}
                className="flex items-center gap-2 text-slate-400 hover:text-amber-400 transition-colors w-full group"
            >
                <div className={`transform transition-transform ${isExpanded ? 'rotate-90' : ''}`}>▶</div>
                <div className="text-sm font-medium uppercase tracking-wider flex items-center gap-2">
                    <span>AI Transparency & Audit</span>
                    {metadata?.prompt_version && (
                        <span className="px-1.5 py-0.5 bg-slate-800 rounded text-xs text-slate-500 font-mono group-hover:bg-slate-700">
                            v{metadata.prompt_version}
                        </span>
                    )}
                </div>
                <div className="flex-1 h-px bg-slate-800 ml-2 group-hover:bg-slate-700" />
            </button>

            {isExpanded && (
                <div className="mt-4 space-y-6 animate-in slide-in-from-top-2 duration-200">

                    {/* Epistemic Anguish Notice (Phase 5) */}
                    <div className="bg-amber-50 border-l-4 border-amber-500 p-3 text-sm text-amber-900 font-mono shadow-sm">
                        <strong>⚠️ Epistemic Notice:</strong> This result was generated by a specific configuration of human choices materialized as code.
                        <br />You remain fully responsible for ignoring, accepting, or negating it.
                    </div>

                    {/* Metadata Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                        <div className="bg-white p-3 rounded border border-slate-200 shadow-sm">
                            <div className="text-slate-500 text-xs mb-1 uppercase tracking-wider font-bold">Configuration</div>
                            <div className="font-mono text-slate-700 truncate" title={promptId}>
                                <span className="text-indigo-600 font-semibold">ID:</span> {promptId}<br />
                                <span className="text-indigo-600 font-semibold">Ver:</span> {promptVersion}
                            </div>
                        </div>
                        <div className="bg-white p-3 rounded border border-slate-200 shadow-sm">
                            <div className="text-slate-500 text-xs mb-1 uppercase tracking-wider font-bold">Execution</div>
                            <div className="font-mono text-slate-700">
                                {metadata?.model_version || 'gpt-4o'}<br />
                                <span className="text-slate-500">Temp:</span> {metadata?.temperature}
                            </div>
                        </div>
                        <div className="bg-white p-3 rounded border border-slate-200 shadow-sm">
                            <div className="text-slate-500 text-xs mb-1 uppercase tracking-wider font-bold">Tokens</div>
                            <div className="font-mono text-slate-700">
                                {metadata?.max_tokens ? `< ${metadata.max_tokens}` : 'Auto'}<br />
                                <span className="text-slate-500">Used:</span> {provenance_chain?.steps.find(s => s.agent === 'openai')?.inputs.prompt_tokens || '?'}
                            </div>
                        </div>
                    </div>

                    {/* Glass Box Data */}
                    <div className="space-y-2">
                        <div className="flex gap-2">
                            <button
                                onClick={() => setShowPrompt(!showPrompt)}
                                className={`px-3 py-1.5 text-xs font-medium rounded border transition-colors ${showPrompt
                                    ? 'bg-slate-200 border-slate-300 text-slate-900 shadow-inner'
                                    : 'bg-white border-slate-300 text-slate-600 hover:bg-slate-50 hover:text-slate-800'
                                    }`}
                            >
                                {showPrompt ? 'Hide Prompt Context' : 'Show Prompt Context'}
                            </button>
                            <button
                                onClick={() => setShowThinking(!showThinking)}
                                className={`px-3 py-1.5 text-xs font-medium rounded border transition-colors ${showThinking
                                    ? 'bg-slate-200 border-slate-300 text-slate-900 shadow-inner'
                                    : 'bg-white border-slate-300 text-slate-600 hover:bg-slate-50 hover:text-slate-800'
                                    }`}
                            >
                                {showThinking ? 'Hide Chain of Thought' : 'Show Chain of Thought'}
                            </button>
                        </div>

                        {showPrompt && (
                            <div className="bg-slate-900 p-4 rounded border border-slate-700 font-mono text-xs text-slate-300 whitespace-pre-wrap max-h-96 overflow-y-auto custom-scrollbar shadow-inner">
                                {metadata?.prompt_used || 'Prompt content not captured in this version.'}
                            </div>
                        )}

                        {showThinking && provenance_chain && (
                            <div className="space-y-4 pt-2">
                                {provenance_chain.steps.map((step, i) => (
                                    <div key={step.step_id} className="relative pl-6 border-l border-slate-300">
                                        <div className="absolute -left-1.5 top-1.5 w-3 h-3 rounded-full bg-indigo-100 border-2 border-indigo-500" />
                                        <div className="text-xs text-slate-500 mb-1 flex justify-between">
                                            <span className="font-semibold text-indigo-700 uppercase">{step.agent}</span>
                                            <span>{new Date(step.timestamp).toLocaleTimeString()}</span>
                                        </div>
                                        <div className="text-sm text-slate-800 font-medium">{step.description}</div>
                                        {step.outputs?.raw_response && (
                                            <div className="mt-2 text-xs font-mono text-slate-600 truncate bg-slate-50 p-1.5 rounded border border-slate-200">
                                                {step.outputs.raw_response}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>

                    {/* Sartrean Rupture Actions (Phase 5) */}
                    <div className="flex flex-col gap-3 pt-4 border-t border-slate-200 mt-4">
                        <div className="flex justify-end gap-3">
                            {!isFlagging ? (
                                <div className="flex items-center gap-2">
                                    <div className="relative group">
                                        <button
                                            className="w-5 h-5 rounded-full border border-slate-300 text-slate-400 text-[10px] flex items-center justify-center hover:text-indigo-600 hover:border-indigo-600 transition-colors"
                                            title="What does this mean?"
                                        >
                                            ?
                                        </button>
                                        <div className="absolute bottom-full right-0 mb-2 w-72 p-3 bg-white rounded-lg shadow-xl border border-slate-200 text-xs hidden group-hover:block z-10 animate-in fade-in zoom-in-95 duration-200 pointer-events-none">
                                            <div className="font-bold text-slate-800 mb-1">Sartrean Negation</div>
                                            <div className="text-slate-600 leading-relaxed">
                                                This is not a bug report. It is a <span className="italic">philosophical refusal</span>.
                                                By flagging, you assert that you reject the AI's generated reality as incomplete or invalid,
                                                preventing it from becoming "petrified" truth.
                                            </div>
                                            <div className="absolute -bottom-1 right-2 w-2 h-2 bg-white border-b border-r border-slate-200 transform rotate-45"></div>
                                        </div>
                                    </div>
                                    <button
                                        onClick={() => setIsFlagging(true)}
                                        className="px-3 py-1.5 text-xs font-medium text-rose-700 bg-rose-50 hover:bg-rose-100 border border-transparent hover:border-rose-200 rounded transition-all flex items-center gap-1.5"
                                    >
                                        <span>🏳️</span> Flag as Unacceptable (Negate)
                                    </button>
                                </div>
                            ) : (
                                <div className="flex items-center gap-2 animate-in fadeIn duration-200 w-full justify-end">
                                    <input
                                        type="text"
                                        placeholder="Justification for negation (e.g., 'Ignores indigenous context')..."
                                        value={flagReason}
                                        onChange={(e) => setFlagReason(e.target.value)}
                                        className="px-3 py-1.5 bg-white border border-slate-300 rounded text-xs text-slate-800 placeholder:text-slate-400 focus:outline-none focus:border-rose-500 focus:ring-1 focus:ring-rose-500/20 w-80 shadow-inner"
                                        autoFocus
                                    />
                                    <button
                                        onClick={async () => {
                                            if (flagReason) {
                                                // 1. Create Proposal (Persist to Redis)
                                                await governanceService.createEpistemicNegationProposal(
                                                    'user_current',
                                                    // analysis 'id' might not be on the type, using safe fallback or hash
                                                    metadata?.timestamp || 'unknown_analysis',
                                                    promptId,
                                                    flagReason,
                                                    sourceId,
                                                    sourceTitle
                                                );

                                                // 2. Notify Parent (Logs/UI)
                                                if (onFlagResult) {
                                                    onFlagResult(flagReason);
                                                }

                                                setIsFlagging(false);
                                                setFlagReason("");
                                            }
                                        }}
                                        disabled={!flagReason}
                                        className="px-3 py-1.5 bg-rose-600 text-white font-medium text-xs rounded shadow-sm hover:bg-rose-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                                    >
                                        Confirm
                                    </button>
                                    <button
                                        onClick={() => setIsFlagging(false)}
                                        className="px-3 py-1.5 text-slate-600 hover:text-slate-800 hover:bg-slate-100 rounded text-xs transition-colors"
                                    >
                                        Cancel
                                    </button>
                                </div>
                            )}

                            <button
                                onClick={() => setShowForkDialog(true)}
                                className="px-3 py-1.5 text-xs font-medium text-amber-700 bg-amber-50 hover:bg-amber-100 border border-transparent hover:border-amber-200 rounded transition-all flex items-center gap-1.5"
                            >
                                <span>⚡</span> Fork This Prompt
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <PromptForkDialog
                isOpen={showForkDialog}
                onClose={() => setShowForkDialog(false)}
                currentPromptId={promptId}
                currentPromptVersion={promptVersion}
                defaultValue={metadata?.prompt_used || ''}
                onSaveFork={async (newContent) => {
                    if (onForkPrompt) {
                        await onForkPrompt(newContent);
                    }
                }}
            />
        </div>
    );
}
